version: '3.5'
x-project-volume:
  &local-files
  type: bind
  source: .
  target: /app

x-shared-volume:
  &shared-files
  type: volume
  source: dist
  target: /app/dist

volumes:
  dist:

services:  
  transpiler:
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - *local-files
      - *shared-files
    command: yarn build
  server:
    build: ./src
    depends_on:
      - "transpiler"
    volumes:
      - *local-files
      - *shared-files
  test:
    build: ./tests
    depends_on:
      - "transpiler"
    volumes:
      - *local-files
      - *shared-files
    command: yarn test